module.exports = {
  content: ['./public/**/*.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      xs: '370px',
      sm: '580px',
      md: '768px',
      base: '910px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1580px',
    },
    fontFamily: {
      // serif: [
      //   'ui-sans-serif',
      //   'system-ui',
      //   '-apple-system',
      //   'BlinkMacSystemFont',
      //   '"Segoe UI"',
      //   'Roboto',
      //   '"Helvetica Neue"',
      //   'Arial',
      //   '"Noto Sans"',
      //   'sans-serif',
      //   '"Apple Color Emoji"',
      //   '"Segoe UI Emoji"',
      //   '"Segoe UI Symbol"',
      //   '"Noto Color Emoji"',
      // ],
      sans: [
        'Bai Jamjuree',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Consolas',
        '"Liberation Mono"',
        'Menlo',
        'monospace',
      ],
    },
    fontSize: {
      xs6: '.25rem',
      xs5: '.375rem',
      xs4: '.5rem',
      xs3: '.625rem',
      xs2: '.75rem',
      xs: '.8rem',
      sm: '.875rem',
      tiny: '.875rem',
      md: '.93rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2rem',
      '5xl': '2.5rem',
      '6xl': '3rem',
      '7xl': '4rem',
      '8xl': '5rem',
    },
    borderWidth: {
      DEFAULT: '1px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
      5: '5px',
      6: '6px',
      8: '8px',
    },
    extend: {
      margin: {
        0.75: '0.1875rem',
        6.5: '1.625rem',
      },
      width: {
        42: '10.5rem',
        88: '22rem',
        100: '30rem',
        125: '38rem',
        150: '45rem',
        200: '60rem',
        250: '75rem',
        350: '350px',
        450: '450px',
      },
      height: {
        620: '620px',
      },
    },
  },
  plugins: [],
};
